# Generated by Django 4.2.4 on 2024-02-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cooment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cooment',
            new_name='Comment',
        ),
    ]
